In [3]:
# !pip install numpy==1.26.2
import numpy as np

In [6]:
a = [1, 2, 3]
b = [4, 5, 6]
print(a + b)

[1, 2, 3, 4, 5, 6]


In [8]:
a = [[1, 2, 3], 
     [4, 5, 6, 7]]

In [37]:
a = np.array([1,2,3,4,5])

In [38]:
type(a)

numpy.ndarray

In [39]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [40]:
b.shape

(2, 3)

In [41]:
a.shape

(5,)

In [42]:
b = np.array([[1],[2],[1],[1],[1]])

In [43]:
b.shape

(5, 1)

In [49]:
zeros = np.zeros((2, 3), dtype = 'int')
print(zeros)

[[0 0 0]
 [0 0 0]]


In [58]:
ones = np.ones((5, 5), dtype='float')
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [55]:
custom = np.full((2, 3), 1.25)
print(custom)

[[1.25 1.25 1.25]
 [1.25 1.25 1.25]]


In [66]:
print(np.eye(N = 4, M = 3, k = -1, order = 'F'))

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [71]:
print(np.eye(N = 2, M = 5, k = 2, order = 'C'))

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [75]:
a = np.arange(12).reshape(3, 4)

In [76]:
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        print(a[i][j])

0
1
2
3
4
5
6
7
8
9
10
11


In [79]:
print(a)
for x in np.nditer(a, order = 'F'):
    print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0
4
8
1
5
9
2
6
10
3
7
11


In [97]:
print(np.arange(5, 20, 2))

[ 5  7  9 11 13 15 17 19]


In [98]:
print(np.linspace(1, 10))

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [103]:
print(np.random.rand(3, 2))

[[0.31186559 0.27104318]
 [0.81471032 0.25883511]
 [0.89385648 0.54767652]]


In [118]:
print(np.random.randint(100, size = (2, 3)))

[[48 98  5]
 [35 40 38]]


In [110]:
np.random.randn(2, 3)

array([[-0.47518445,  1.34927361,  1.83443467],
       [ 0.21639389,  1.21634986, -0.43020666]])

In [120]:
np.random.random((3, 2))

array([[0.34009918, 0.6706093 ],
       [0.70060802, 0.44571024],
       [0.92709283, 0.10707632]])

In [122]:
np.random.random_integers(100, size = (2, 3))

C:\Users\bhatt\AppData\Local\Temp\ipykernel_31908\1277461192.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 100 + 1) instead
  np.random.random_integers(100, size = (2, 3))


array([[41, 32, 97],
       [18, 51,  2]])

In [125]:
np.random.random_sample?

In [126]:
a = np.array([[1,2,3], 
              [4,5,6]])

In [128]:
b = np.array([[1,2,3], 
              [4,5,6]])

In [129]:
a+b

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [130]:
a - b

array([[0, 0, 0],
       [0, 0, 0]])

In [131]:
a * b

array([[ 1,  4,  9],
       [16, 25, 36]])

In [132]:
a/b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [133]:
np.add(a, b)

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [134]:
np.subtract(a, b)

array([[0, 0, 0],
       [0, 0, 0]])

In [135]:
np.multiply(a, b)

array([[ 1,  4,  9],
       [16, 25, 36]])

In [139]:
np.matmul(a, b.T)

array([[14, 32],
       [32, 77]])

In [142]:
a@b.T

array([[14, 32],
       [32, 77]])

In [143]:
# np.dot

In [167]:
a = np.array([[[1, 2, 3],
              [4, 5, 6], 
              [7, 8, 9]], 
             [[1, 2, 3],
              [4, 5, 6], 
              [7, 8, 9]]])
print(a.shape)

(2, 3, 3)


In [175]:
np.sum(a, axis = 2)

array([[ 6, 15, 24],
       [ 6, 15, 24]])

In [172]:
a

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])