In [1]:
# !pip install numpy==1.26.2
import numpy as np

In [2]:
a = [1, 2, 3]
b = [4, 5, 6]
print(a + b)

[1, 2, 3, 4, 5, 6]


In [3]:
a = [[1, 2, 3], 
     [4, 5, 6, 7]]

In [4]:
a = np.array([1,2,3,4,5])

In [5]:
type(a)

numpy.ndarray

In [6]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [7]:
b.shape

(2, 3)

In [8]:
a.shape

(5,)

In [9]:
b = np.array([[1],[2],[1],[1],[1]])

In [10]:
b.shape

(5, 1)

In [11]:
zeros = np.zeros((2, 3), dtype = 'int')
print(zeros)

[[0 0 0]
 [0 0 0]]


In [12]:
ones = np.ones((5, 5), dtype='float')
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [13]:
custom = np.full((2, 3), 1.25)
print(custom)

[[1.25 1.25 1.25]
 [1.25 1.25 1.25]]


In [14]:
print(np.eye(N = 4, M = 3, k = -1, order = 'F'))

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
print(np.eye(N = 2, M = 5, k = 2, order = 'C'))

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [16]:
a = np.arange(12).reshape(3, 4)

In [17]:
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        print(a[i][j])

0
1
2
3
4
5
6
7
8
9
10
11


In [18]:
print(a)
for x in np.nditer(a, order = 'F'):
    print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0
4
8
1
5
9
2
6
10
3
7
11


In [19]:
print(np.arange(5, 20, 2))

[ 5  7  9 11 13 15 17 19]


In [44]:
print(np.linspace(1, 10, 100))

[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.09090909  7.18181818  7.27272727  7.36363636  7.45454545
  7.54545455  7.63636364  7.72727273  7.81818182  7.90909091  8.
  8.09090909  8.18181818  8.27272727  8.36363636  8.45454545  8.545

In [21]:
print(np.random.rand(3, 2))

[[0.13363439 0.68830357]
 [0.02652008 0.42862906]
 [0.09166078 0.79627322]]


In [22]:
print(np.random.randint(100, size = (2, 3)))

[[12 39  2]
 [83 26 25]]


In [54]:
np.random.randn(2, 3)

array([[-1.58347101, -0.39553718,  0.8848708 ],
       [ 2.9888514 ,  0.55345266,  0.41864767]])

In [24]:
np.random.random((3, 2))

array([[0.29858998, 0.48260131],
       [0.71721444, 0.9541327 ],
       [0.96887281, 0.08793082]])

In [25]:
np.random.random_integers(100, size = (2, 3))

C:\Users\bhatt\AppData\Local\Temp\ipykernel_20308\1277461192.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 100 + 1) instead
  np.random.random_integers(100, size = (2, 3))


array([[73, 69, 76],
       [82, 22, 47]])

In [55]:
np.random.random_sample?

In [27]:
a = np.array([[1,2,3], 
              [4,5,6]])

In [28]:
b = np.array([[1,2,3], 
              [4,5,6]])

In [29]:
a+b

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [30]:
a - b

array([[0, 0, 0],
       [0, 0, 0]])

In [31]:
a * b

array([[ 1,  4,  9],
       [16, 25, 36]])

In [32]:
a/b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [33]:
np.add(a, b)

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [34]:
np.subtract(a, b)

array([[0, 0, 0],
       [0, 0, 0]])

In [35]:
np.multiply(a, b)

array([[ 1,  4,  9],
       [16, 25, 36]])

In [36]:
np.matmul(a, b.T)

array([[14, 32],
       [32, 77]])

In [37]:
a@b.T

array([[14, 32],
       [32, 77]])

In [38]:
# np.dot

In [57]:
a = np.array([[[1, 2, 3],
              [4, 5, 6], 
              [7, 8, 9]], 
             [[1, 2, 3],
              [4, 5, 6], 
              [7, 8, 9]]])
print(a.shape)

(2, 3, 3)


In [67]:
np.sum(a, axis = -1)

array([[ 6, 15, 24],
       [ 6, 15, 24]])

In [41]:
a

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [42]:
np.eye?